#KNN_sklearn

In [1]:
import pandas as pd

In [21]:
data = pd.read_csv("iris.csv", names=["s1","sw","pl","pw","class"])

data.head()

    s1   sw   pl   pw        class
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

K-En Yakın Komşu (KNN) sınıflandırıcısıdır. Yeni bir örneğin etiketini, eğitim verisindeki en yakın k komşusuna bakarak tahmin eder (ör. k=5).

In [23]:
Y=data.pop("class")
X=data

In [27]:
train_x, test_x, train_y, test_y =train_test_split(X,Y,test_size=0.2)

In [25]:
from sklearn.preprocessing import StandardScaler

In [28]:
mms=StandardScaler()
mms.fit(train_x)
train_x=mms.transform(train_x)
test_x=mms.transform(test_x)

#eğitim verisini dönüştürüyor

In [29]:
knn_model=KNeighborsClassifier(n_neighbors=3)
knn_model.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=3)

In [30]:
knn_model.predict([[6.3,2.5,5.0,1.9]])

array(['Iris-virginica'], dtype=object)

In [31]:
len(test_x)

30

In [36]:
predicted_y=knn_model.predict(test_x)
predicted_y

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

In [38]:
for i in predicted_y:
  pass
true_counter=0
index_counter=0
for prediction,real in zip(predicted_y,test_y):
  if prediction==real:
    true_counter+=1
  else:
    print(prediction,real,index_counter)
    index_counter+=1

Iris-versicolor Iris-virginica 0
Iris-virginica Iris-versicolor 1

In [39]:
total_test_samples=len(test_y)
oran=round((true_counter/total_test_samples)*100,2)
print("Oran:%",oran)

Oran:% 93.33

#Knn

In [40]:
import pandas as d

In [42]:
data = pd.read_csv("iris.csv", names=["sl","sw","pl","pw","class"])
data.head()

    sl   sw   pl   pw        class
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [43]:
sample_1 = [4.8,3.0,1.4,0.1] # setosa
sample_2 = [6.4,2.9,4.3,1.3] # versicolor
sample_3 = [6.3,2.5,5.0,1.9] # virgina

K = 3

In [44]:
def calculate_distance(ins1,ins2):
  sum=0
  for index in range(len(ins1)):
    sum+=(ins1[index]-ins2[index])**2
  sqr=sum**0.5
  return sqr

In [45]:
#test distance function
sample_a = [1,1,2,3,5]
sample_b = [2,2,2,3,4]
calculate_distance(sample_a,sample_b)

1.7320508075688772

In [47]:
print("Sınıflandırma : ",sample_2 )
distance_list=[]
for index,row in data.iterrows():
  data_sample=row.values[:-1]
  true_class=row.values[-1]
  distance=calculate_distance(data_sample,sample_2)
  print(data_sample,true_class,distance)
  distance_list.append([distance,true_class,distance])

Sınıflandırma :  [6.4, 2.9, 4.3, 1.3]
[5.1 3.5 1.4 0.2] Iris-setosa 3.416138170507745
[4.9 3.0 1.4 0.2] Iris-setosa 3.4467375879228173
[4.7 3.2 1.3 0.2] Iris-setosa 3.6318039594669758
[4.6 3.1 1.5 0.2] Iris-setosa 3.511409973215888
[5.0 3.6 1.4 0.2] Iris-setosa 3.474190553208042
[5.4 3.9 1.7 0.4] Iris-setosa 3.0935416596516037
[4.6 3.4 1.4 0.3] Iris-setosa 3.5916569992135945
[5.0 3.4 1.5 0.2] Iris-setosa 3.3555923471125038
[4.4 2.9 1.4 0.2] Iris-setosa 3.6905284174491872
[4.9 3.1 1.5 0.1] Iris-setosa 3.4014702703389896
[5.4 3.7 1.5 0.2] Iris-setosa 3.269556544854363
[4.8 3.4 1.6 0.2] Iris-setosa 3.3630343441600474
[4.3 3.0 1.1 0.1] Iris-setosa 4.012480529547776
[5.8 4.0 1.2 0.2] Iris-setosa 3.5199431813596083
[5.7 4.4 1.5 0.4] Iris-setosa 3.374907406137241
[5.4 3.9 1.3 0.4] Iris-setosa 3.4365680554879168
[5.1 3.5 1.4 0.3] Iris-setosa 3.385262175962152
[5.7 3.8 1.7 0.3] Iris-setosa 3.009983388658482
[5.1 3.8 1.5 0.3] Iris-setosa 3.3674916480965473
[5.4 3.4 1.7 0.2] Iris-setosa 3.036445290137795
[5.1 3.7 1.5 0.4] Iris-setosa 3.3136083051561784
[4.6 3.6 1.0 0.2] Iris-setosa 3.9786932528155523
[5.1 3.3 1.7 0.5] Iris-setosa 3.0413812651491097
[4.8 3.4 1.9 0.2] Iris-setosa 3.1272991542223783
[5.0 3.0 1.6 0.2] Iris-setosa 3.2357379374726873
[5.0 3.4 1.6 0.4] Iris-setosa 3.2109188716004646
[5.2 3.5 1.5 0.2] Iris-setosa 3.2939338184001206
[5.2 3.4 1.4 0.2] Iris-setosa 3.363034344160048
[4.7 3.2 1.6 0.2] Iris-setosa 3.388214869219483
[4.8 3.1 1.6 0.2] Iris-setosa 3.3316662497915366
[5.4 3.4 1.5 0.4] Iris-setosa 3.146426544510455
[5.2 4.1 1.5 0.1] Iris-setosa 3.4871191548325386
[5.5 4.2 1.4 0.2] Iris-setosa 3.4813790371058424
[4.9 3.1 1.5 0.1] Iris-setosa 3.4014702703389896
[5.0 3.2 1.2 0.2] Iris-setosa 3.5874782229304194
[5.5 3.5 1.3 0.2] Iris-setosa 3.3734255586866007
[4.9 3.1 1.5 0.1] Iris-setosa 3.4014702703389896
[4.4 3.0 1.3 0.2] Iris-setosa 3.7709415269929605
[5.1 3.4 1.5 0.2] Iris-setosa 3.3151168908501556
[5.0 3.5 1.3 0.3] Iris-setosa 3.509985754956849
[4.5 2.3 1.3 0.3] Iris-setosa 3.737646318206152
[4.4 3.2 1.3 0.2] Iris-setosa 3.7815340802378077
[5.0 3.5 1.6 0.6] Iris-setosa 3.1780497164141406
[5.1 3.8 1.9 0.4] Iris-setosa 3.01164406927512
[4.8 3.0 1.4 0.3] Iris-setosa 3.4612136599753565
[5.1 3.8 1.6 0.2] Iris-setosa 3.3166247903554
[4.6 3.2 1.4 0.2] Iris-setosa 3.598610843089317
[5.3 3.7 1.5 0.2] Iris-setosa 3.301514803843836
[5.0 3.3 1.4 0.2] Iris-setosa 3.426368339802363
[7.0 3.2 4.7 1.4] Iris-versicolor 0.7874007874011811
[6.4 3.2 4.5 1.5] Iris-versicolor 0.4123105625617663
[6.9 3.1 4.9 1.5] Iris-versicolor 0.830662386291808
[5.5 2.3 4.0 1.3] Iris-versicolor 1.1224972160321827
[6.5 2.8 4.6 1.5] Iris-versicolor 0.3872983346207415
[5.7 2.8 4.5 1.3] Iris-versicolor 0.7348469228349537
[6.3 3.3 4.7 1.6] Iris-versicolor 0.6480740698407863
[4.9 2.4 3.3 1.0] Iris-versicolor 1.8947295321496416
[6.6 2.9 4.6 1.3] Iris-versicolor 0.3605551275463984
[5.2 2.7 3.9 1.4] Iris-versicolor 1.284523257866513
[5.0 2.0 3.5 1.0] Iris-versicolor 1.8708286933869709
[5.9 3.0 4.2 1.5] Iris-versicolor 0.5567764362830021
[6.0 2.2 4.0 1.0] Iris-versicolor 0.9110433579144298
[6.1 2.9 4.7 1.4] Iris-versicolor 0.5099019513592792
[5.6 2.9 3.6 1.3] Iris-versicolor 1.0630145812734653
[6.7 3.1 4.4 1.4] Iris-versicolor 0.38729833462074176
[5.6 3.0 4.5 1.5] Iris-versicolor 0.8544003745317538
[5.8 2.7 4.1 1.0] Iris-versicolor 0.7280109889280523
[6.2 2.2 4.5 1.5] Iris-versicolor 0.7810249675906652
[5.6 2.5 3.9 1.1] Iris-versicolor 1.0000000000000004
[5.9 3.2 4.8 1.8] Iris-versicolor 0.9165151389911681
[6.1 2.8 4.0 1.3] Iris-versicolor 0.4358898943540677
[6.3 2.5 4.9 1.5] Iris-versicolor 0.7549834435270755
[6.1 2.8 4.7 1.2] Iris-versicolor 0.5196152422706639
[6.6 3.0 4.4 1.4] Iris-versicolor 0.2645751311064587
[6.8 2.8 4.8 1.4] Iris-versicolor 0.6557438524301997
[6.7 3.0 5.0 1.7] Iris-versicolor 0.8660254037844387
[6.0 2.9 4.5 1.5] Iris-versicolor 0.48989794855663593
[5.7 2.6 3.5 1.0] Iris-versicolor 1.1445523142259597
[5.5 2.4 3.8 1.1] Iris-versicolor 1.1618950038622253
[5.5 2.4 3.7 1.0] Iris-versicolor 1.2288205727444508
[5.8 2.7 3.9 1.2] Iris-versicolor 0.7549834435270754
[6.0 2.7 5.1 1.6] Iris-versicolor 0.9643650760992954
[5.4 3.0 4.5 1.5] Iris-versicolor 1.044030650891055
[6.0 3.4 4.5 1.6] Iris-versicolor 0.7348469228349537
[6.7 3.1 4.7 1.5] Iris-versicolor 0.5744562646538031
[6.3 2.3 4.4 1.3] Iris-versicolor 0.6164414002968979
[5.6 3.0 4.1 1.3] Iris-versicolor 0.8306623862918082
[5.5 2.5 4.0 1.3] Iris-versicolor 1.0295630140987002
[5.5 2.6 4.4 1.2] Iris-versicolor 0.9591663046625443
[6.1 3.0 4.6 1.4] Iris-versicolor 0.4472135954999583
[5.8 2.6 4.0 1.2] Iris-versicolor 0.7416198487095667
[5.0 2.3 3.3 1.0] Iris-versicolor 1.846618531261939
[5.6 2.7 4.2 1.3] Iris-versicolor 0.8306623862918081
[5.7 3.0 4.2 1.2] Iris-versicolor 0.721110255092798
[5.7 2.9 4.2 1.3] Iris-versicolor 0.7071067811865477
[6.2 2.9 4.3 1.3] Iris-versicolor 0.20000000000000018
[5.1 2.5 3.0 1.1] Iris-versicolor 1.8920887928424504
[5.7 2.8 4.1 1.3] Iris-versicolor 0.7348469228349537
[6.3 3.3 6.0 2.5] Iris-virginica 2.1213203435596424
[5.8 2.7 5.1 1.9] Iris-virginica 1.1832159566199232
[7.1 3.0 5.9 2.1] Iris-virginica 1.9235384061671348
[6.3 2.9 5.6 1.8] Iris-virginica 1.3964240043768938
[6.5 3.0 5.8 2.2] Iris-virginica 1.7549928774784245
[7.6 3.0 6.6 2.1] Iris-virginica 2.7166155414412243
[4.9 2.5 4.5 1.7] Iris-virginica 1.6155494421403513
[7.3 2.9 6.3 1.8] Iris-virginica 2.2494443758403984
[6.7 2.5 5.8 1.8] Iris-virginica 1.6583123951777
[7.2 3.6 6.1 2.5] Iris-virginica 2.41039415863879
[6.5 3.2 5.1 2.0] Iris-virginica 1.1090536506409416
[6.4 2.7 5.3 1.9] Iris-virginica 1.1832159566199232
[6.8 3.0 5.5 2.1] Iris-virginica 1.5
[5.7 2.5 5.0 2.0] Iris-virginica 1.2767145334803707
[5.8 2.8 5.1 2.4] Iris-virginica 1.489966442575134
[6.4 3.2 5.3 2.3] Iris-virginica 1.445683229480096
[6.5 3.0 5.5 1.8] Iris-virginica 1.3076696830622023
[7.7 3.8 6.7 2.2] Iris-virginica 3.01164406927512
[7.7 2.6 6.9 2.3] Iris-virginica 3.0886890422961004
[6.0 2.2 5.0 1.5] Iris-virginica 1.0862780491200217
[6.9 3.2 5.7 2.3] Iris-virginica 1.8165902124584952
[5.6 2.8 4.9 2.0] Iris-virginica 1.2247448713915898
[7.7 2.8 6.7 2.0] Iris-virginica 2.819574435974337
[6.3 2.7 4.9 1.8] Iris-virginica 0.8124038404635964
[6.7 3.3 5.7 2.1] Iris-virginica 1.6881943016134136
[7.2 3.2 6.0 1.8] Iris-virginica 1.9672315572906003
[6.2 2.8 4.8 1.8] Iris-virginica 0.7416198487095663
[6.1 3.0 4.9 1.8] Iris-virginica 0.8426149773176365
[6.4 2.8 5.6 2.1] Iris-virginica 1.5297058540778354
[7.2 3.0 5.8 1.6] Iris-virginica 1.729161646579058
[7.4 2.8 6.1 1.9] Iris-virginica 2.1470910553583886
[7.9 3.8 6.4 2.0] Iris-virginica 2.821347195933177
[6.4 2.8 5.6 2.2] Iris-virginica 1.5842979517754858
[6.3 2.8 5.1 1.5] Iris-virginica 0.8366600265340753
[6.1 2.6 5.6 1.4] Iris-virginica 1.3711309200802089
[7.7 3.0 6.1 2.3] Iris-virginica 2.4372115213907874
[6.3 3.4 5.6 2.4] Iris-virginica 1.7776388834631176
[6.4 3.1 5.5 1.8] Iris-virginica 1.3152946437965907
[6.0 3.0 4.8 1.8] Iris-virginica 0.8185352771872452
[6.9 3.1 5.4 2.1] Iris-virginica 1.46287388383278
[6.7 3.1 5.6 2.4] Iris-virginica 1.7406895185529208
[6.9 3.1 5.1 2.3] Iris-virginica 1.38924439894498
[5.8 2.7 5.1 1.9] Iris-virginica 1.1832159566199232
[6.8 3.2 5.9 2.3] Iris-virginica 1.9519221295943137
[6.7 3.3 5.7 2.5] Iris-virginica 1.9104973174542803
[6.7 3.0 5.2 2.3] Iris-virginica 1.3820274961085255
[6.5 3.0 5.2 2.0] Iris-virginica 1.148912529307606
[6.2 3.4 5.4 2.3] Iris-virginica 1.58113883008419
[5.9 3.0 5.1 1.8] Iris-virginica 1.0723805294763606

In [49]:
distance_list

[[3.416138170507745, 'Iris-setosa', 3.416138170507745],
 [3.4467375879228173, 'Iris-setosa', 3.4467375879228173],
 [3.6318039594669758, 'Iris-setosa', 3.6318039594669758],
 [3.511409973215888, 'Iris-setosa', 3.511409973215888],
 [3.474190553208042, 'Iris-setosa', 3.474190553208042],
 [3.0935416596516037, 'Iris-setosa', 3.0935416596516037],
 [3.5916569992135945, 'Iris-setosa', 3.5916569992135945],
 [3.3555923471125038, 'Iris-setosa', 3.3555923471125038],
 [3.6905284174491872, 'Iris-setosa', 3.6905284174491872],
 [3.4014702703389896, 'Iris-setosa', 3.4014702703389896],
 [3.269556544854363, 'Iris-setosa', 3.269556544854363],
 [3.3630343441600474, 'Iris-setosa', 3.3630343441600474],
 [4.012480529547776, 'Iris-setosa', 4.012480529547776],
 [3.5199431813596083, 'Iris-setosa', 3.5199431813596083],
 [3.374907406137241, 'Iris-setosa', 3.374907406137241],
 [3.4365680554879168, 'Iris-setosa', 3.4365680554879168],
 [3.385262175962152, 'Iris-setosa', 3.385262175962152],
 [3.009983388658482, 'Iris-setosa', 3.009983388658482],
 [3.3674916480965473, 'Iris-setosa', 3.3674916480965473],
 [3.036445290137795, 'Iris-setosa', 3.036445290137795],
 [3.3136083051561784, 'Iris-setosa', 3.3136083051561784],
 [3.9786932528155523, 'Iris-setosa', 3.9786932528155523],
 [3.0413812651491097, 'Iris-setosa', 3.0413812651491097],
 [3.1272991542223783, 'Iris-setosa', 3.1272991542223783],
 [3.2357379374726873, 'Iris-setosa', 3.2357379374726873],
 [3.2109188716004646, 'Iris-setosa', 3.2109188716004646],
 [3.2939338184001206, 'Iris-setosa', 3.2939338184001206],
 [3.363034344160048, 'Iris-setosa', 3.363034344160048],
 [3.388214869219483, 'Iris-setosa', 3.388214869219483],
 [3.3316662497915366, 'Iris-setosa', 3.3316662497915366],
 [3.146426544510455, 'Iris-setosa', 3.146426544510455],
 [3.4871191548325386, 'Iris-setosa', 3.4871191548325386],
 [3.4813790371058424, 'Iris-setosa', 3.4813790371058424],
 [3.4014702703389896, 'Iris-setosa', 3.4014702703389896],
 [3.5874782229304194, 'Iris-setosa', 3.5874782229304194],
 [3.3734255586866007, 'Iris-setosa', 3.3734255586866007],
 [3.4014702703389896, 'Iris-setosa', 3.4014702703389896],
 [3.7709415269929605, 'Iris-setosa', 3.7709415269929605],
 [3.3151168908501556, 'Iris-setosa', 3.3151168908501556],
 [3.509985754956849, 'Iris-setosa', 3.509985754956849],
 [3.737646318206152, 'Iris-setosa', 3.737646318206152],
 [3.7815340802378077, 'Iris-setosa', 3.7815340802378077],
 [3.1780497164141406, 'Iris-setosa', 3.1780497164141406],
 [3.01164406927512, 'Iris-setosa', 3.01164406927512],
 [3.4612136599753565, 'Iris-setosa', 3.4612136599753565],
 [3.3166247903554, 'Iris-setosa', 3.3166247903554],
 [3.598610843089317, 'Iris-setosa', 3.598610843089317],
 [3.301514803843836, 'Iris-setosa', 3.301514803843836],
 [3.426368339802363, 'Iris-setosa', 3.426368339802363],
 [0.7874007874011811, 'Iris-versicolor', 0.7874007874011811],
 [0.4123105625617663, 'Iris-versicolor', 0.4123105625617663],
 [0.830662386291808, 'Iris-versicolor', 0.830662386291808],
 [1.1224972160321827, 'Iris-versicolor', 1.1224972160321827],
 [0.3872983346207415, 'Iris-versicolor', 0.3872983346207415],
 [0.7348469228349537, 'Iris-versicolor', 0.7348469228349537],
 [0.6480740698407863, 'Iris-versicolor', 0.6480740698407863],
 [1.8947295321496416, 'Iris-versicolor', 1.8947295321496416],
 [0.3605551275463984, 'Iris-versicolor', 0.3605551275463984],
 [1.284523257866513, 'Iris-versicolor', 1.284523257866513],
 [1.8708286933869709, 'Iris-versicolor', 1.8708286933869709],
 [0.5567764362830021, 'Iris-versicolor', 0.5567764362830021],
 [0.9110433579144298, 'Iris-versicolor', 0.9110433579144298],
 [0.5099019513592792, 'Iris-versicolor', 0.5099019513592792],
 [1.0630145812734653, 'Iris-versicolor', 1.0630145812734653],
 [0.38729833462074176, 'Iris-versicolor', 0.38729833462074176],
 [0.8544003745317538, 'Iris-versicolor', 0.8544003745317538],
 [0.7280109889280523, 'Iris-versicolor', 0.7280109889280523],
 [0.7810249675906652, 'Iris-versicolor', 0.7810249675906652],
 [1.0000000000000004, 'Iris-versicolor', 1.0000000000000004],
 [0.9165151389911681, 'Iris-versicolor', 0.9165151389911681],
 [0.4358898943540677, 'Iris-versicolor', 0.4358898943540677],
 [0.7549834435270755, 'Iris-versicolor', 0.7549834435270755],
 [0.5196152422706639, 'Iris-versicolor', 0.5196152422706639],
 [0.2645751311064587, 'Iris-versicolor', 0.2645751311064587],
 [0.6557438524301997, 'Iris-versicolor', 0.6557438524301997],
 [0.8660254037844387, 'Iris-versicolor', 0.8660254037844387],
 [0.48989794855663593, 'Iris-versicolor', 0.48989794855663593],
 [1.1445523142259597, 'Iris-versicolor', 1.1445523142259597],
 [1.1618950038622253, 'Iris-versicolor', 1.1618950038622253],
 [1.2288205727444508, 'Iris-versicolor', 1.2288205727444508],
 [0.7549834435270754, 'Iris-versicolor', 0.7549834435270754],
 [0.9643650760992954, 'Iris-versicolor', 0.9643650760992954],
 [1.044030650891055, 'Iris-versicolor', 1.044030650891055],
 [0.7348469228349537, 'Iris-versicolor', 0.7348469228349537],
 [0.5744562646538031, 'Iris-versicolor', 0.5744562646538031],
 [0.6164414002968979, 'Iris-versicolor', 0.6164414002968979],
 [0.8306623862918082, 'Iris-versicolor', 0.8306623862918082],
 [1.0295630140987002, 'Iris-versicolor', 1.0295630140987002],
 [0.9591663046625443, 'Iris-versicolor', 0.9591663046625443],
 [0.4472135954999583, 'Iris-versicolor', 0.4472135954999583],
 [0.7416198487095667, 'Iris-versicolor', 0.7416198487095667],
 [1.846618531261939, 'Iris-versicolor', 1.846618531261939],
 [0.8306623862918081, 'Iris-versicolor', 0.8306623862918081],
 [0.721110255092798, 'Iris-versicolor', 0.721110255092798],
 [0.7071067811865477, 'Iris-versicolor', 0.7071067811865477],
 [0.20000000000000018, 'Iris-versicolor', 0.20000000000000018],
 [1.8920887928424504, 'Iris-versicolor', 1.8920887928424504],
 [0.7348469228349537, 'Iris-versicolor', 0.7348469228349537],
 [2.1213203435596424, 'Iris-virginica', 2.1213203435596424],
 [1.1832159566199232, 'Iris-virginica', 1.1832159566199232],
 [1.9235384061671348, 'Iris-virginica', 1.9235384061671348],
 [1.3964240043768938, 'Iris-virginica', 1.3964240043768938],
 [1.7549928774784245, 'Iris-virginica', 1.7549928774784245],
 [2.7166155414412243, 'Iris-virginica', 2.7166155414412243],
 [1.6155494421403513, 'Iris-virginica', 1.6155494421403513],
 [2.2494443758403984, 'Iris-virginica', 2.2494443758403984],
 [1.6583123951777, 'Iris-virginica', 1.6583123951777],
 [2.41039415863879, 'Iris-virginica', 2.41039415863879],
 [1.1090536506409416, 'Iris-virginica', 1.1090536506409416],
 [1.1832159566199232, 'Iris-virginica', 1.1832159566199232],
 [1.5, 'Iris-virginica', 1.5],
 [1.2767145334803707, 'Iris-virginica', 1.2767145334803707],
 [1.489966442575134, 'Iris-virginica', 1.489966442575134],
 [1.445683229480096, 'Iris-virginica', 1.445683229480096],
 [1.3076696830622023, 'Iris-virginica', 1.3076696830622023],
 [3.01164406927512, 'Iris-virginica', 3.01164406927512],
 [3.0886890422961004, 'Iris-virginica', 3.0886890422961004],
 [1.0862780491200217, 'Iris-virginica', 1.0862780491200217],
 [1.8165902124584952, 'Iris-virginica', 1.8165902124584952],
 [1.2247448713915898, 'Iris-virginica', 1.2247448713915898],
 [2.819574435974337, 'Iris-virginica', 2.819574435974337],
 [0.8124038404635964, 'Iris-virginica', 0.8124038404635964],
 [1.6881943016134136, 'Iris-virginica', 1.6881943016134136],
 [1.9672315572906003, 'Iris-virginica', 1.9672315572906003],
 [0.7416198487095663, 'Iris-virginica', 0.7416198487095663],
 [0.8426149773176365, 'Iris-virginica', 0.8426149773176365],
 [1.5297058540778354, 'Iris-virginica', 1.5297058540778354],
 [1.729161646579058, 'Iris-virginica', 1.729161646579058],
 [2.1470910553583886, 'Iris-virginica', 2.1470910553583886],
 [2.821347195933177, 'Iris-virginica', 2.821347195933177],
 [1.5842979517754858, 'Iris-virginica', 1.5842979517754858],
 [0.8366600265340753, 'Iris-virginica', 0.8366600265340753],
 [1.3711309200802089, 'Iris-virginica', 1.3711309200802089],
 [2.4372115213907874, 'Iris-virginica', 2.4372115213907874],
 [1.7776388834631176, 'Iris-virginica', 1.7776388834631176],
 [1.3152946437965907, 'Iris-virginica', 1.3152946437965907],
 [0.8185352771872452, 'Iris-virginica', 0.8185352771872452],
 [1.46287388383278, 'Iris-virginica', 1.46287388383278],
 [1.7406895185529208, 'Iris-virginica', 1.7406895185529208],
 [1.38924439894498, 'Iris-virginica', 1.38924439894498],
 [1.1832159566199232, 'Iris-virginica', 1.1832159566199232],
 [1.9519221295943137, 'Iris-virginica', 1.9519221295943137],
 [1.9104973174542803, 'Iris-virginica', 1.9104973174542803],
 [1.3820274961085255, 'Iris-virginica', 1.3820274961085255],
 [1.148912529307606, 'Iris-virginica', 1.148912529307606],
 [1.58113883008419, 'Iris-virginica', 1.58113883008419],
 [1.0723805294763606, 'Iris-virginica', 1.0723805294763606]]

In [50]:
sorted_distance_list=sorted(distance_list,key=lambda x:x[1])
print(sorted_distance_list)

[[3.416138170507745, 'Iris-setosa', 3.416138170507745], [3.4467375879228173, 'Iris-setosa', 3.4467375879228173], [3.6318039594669758, 'Iris-setosa', 3.6318039594669758], [3.511409973215888, 'Iris-setosa', 3.511409973215888], [3.474190553208042, 'Iris-setosa', 3.474190553208042], [3.0935416596516037, 'Iris-setosa', 3.0935416596516037], [3.5916569992135945, 'Iris-setosa', 3.5916569992135945], [3.3555923471125038, 'Iris-setosa', 3.3555923471125038], [3.6905284174491872, 'Iris-setosa', 3.6905284174491872], [3.4014702703389896, 'Iris-setosa', 3.4014702703389896], [3.269556544854363, 'Iris-setosa', 3.269556544854363], [3.3630343441600474, 'Iris-setosa', 3.3630343441600474], [4.012480529547776, 'Iris-setosa', 4.012480529547776], [3.5199431813596083, 'Iris-setosa', 3.5199431813596083], [3.374907406137241, 'Iris-setosa', 3.374907406137241], [3.4365680554879168, 'Iris-setosa', 3.4365680554879168], [3.385262175962152, 'Iris-setosa', 3.385262175962152], [3.009983388658482, 'Iris-setosa', 3.009983388658482], [3.3674916480965473, 'Iris-setosa', 3.3674916480965473], [3.036445290137795, 'Iris-setosa', 3.036445290137795], [3.3136083051561784, 'Iris-setosa', 3.3136083051561784], [3.9786932528155523, 'Iris-setosa', 3.9786932528155523], [3.0413812651491097, 'Iris-setosa', 3.0413812651491097], [3.1272991542223783, 'Iris-setosa', 3.1272991542223783], [3.2357379374726873, 'Iris-setosa', 3.2357379374726873], [3.2109188716004646, 'Iris-setosa', 3.2109188716004646], [3.2939338184001206, 'Iris-setosa', 3.2939338184001206], [3.363034344160048, 'Iris-setosa', 3.363034344160048], [3.388214869219483, 'Iris-setosa', 3.388214869219483], [3.3316662497915366, 'Iris-setosa', 3.3316662497915366], [3.146426544510455, 'Iris-setosa', 3.146426544510455], [3.4871191548325386, 'Iris-setosa', 3.4871191548325386], [3.4813790371058424, 'Iris-setosa', 3.4813790371058424], [3.4014702703389896, 'Iris-setosa', 3.4014702703389896], [3.5874782229304194, 'Iris-setosa', 3.5874782229304194], [3.3734255586866007, 'Iris-setosa', 3.3734255586866007], [3.4014702703389896, 'Iris-setosa', 3.4014702703389896], [3.7709415269929605, 'Iris-setosa', 3.7709415269929605], [3.3151168908501556, 'Iris-setosa', 3.3151168908501556], [3.509985754956849, 'Iris-setosa', 3.509985754956849], [3.737646318206152, 'Iris-setosa', 3.737646318206152], [3.7815340802378077, 'Iris-setosa', 3.7815340802378077], [3.1780497164141406, 'Iris-setosa', 3.1780497164141406], [3.01164406927512, 'Iris-setosa', 3.01164406927512], [3.4612136599753565, 'Iris-setosa', 3.4612136599753565], [3.3166247903554, 'Iris-setosa', 3.3166247903554], [3.598610843089317, 'Iris-setosa', 3.598610843089317], [3.301514803843836, 'Iris-setosa', 3.301514803843836], [3.426368339802363, 'Iris-setosa', 3.426368339802363], [0.7874007874011811, 'Iris-versicolor', 0.7874007874011811], [0.4123105625617663, 'Iris-versicolor', 0.4123105625617663], [0.830662386291808, 'Iris-versicolor', 0.830662386291808], [1.1224972160321827, 'Iris-versicolor', 1.1224972160321827], [0.3872983346207415, 'Iris-versicolor', 0.3872983346207415], [0.7348469228349537, 'Iris-versicolor', 0.7348469228349537], [0.6480740698407863, 'Iris-versicolor', 0.6480740698407863], [1.8947295321496416, 'Iris-versicolor', 1.8947295321496416], [0.3605551275463984, 'Iris-versicolor', 0.3605551275463984], [1.284523257866513, 'Iris-versicolor', 1.284523257866513], [1.8708286933869709, 'Iris-versicolor', 1.8708286933869709], [0.5567764362830021, 'Iris-versicolor', 0.5567764362830021], [0.9110433579144298, 'Iris-versicolor', 0.9110433579144298], [0.5099019513592792, 'Iris-versicolor', 0.5099019513592792], [1.0630145812734653, 'Iris-versicolor', 1.0630145812734653], [0.38729833462074176, 'Iris-versicolor', 0.38729833462074176], [0.8544003745317538, 'Iris-versicolor', 0.8544003745317538], [0.7280109889280523, 'Iris-versicolor', 0.7280109889280523], [0.7810249675906652, 'Iris-versicolor', 0.7810249675906652], [1.0000000000000004, 'Iris-versicolor', 1.0000000000000004], [0.9165151389911681, 'Iris-versicolor', 0.9165151389911681], [0.4358898943540677, 'Iris-versicolor', 0.4358898943540677], [0.7549834435270755, 'Iris-versicolor', 0.7549834435270755], [0.5196152422706639, 'Iris-versicolor', 0.5196152422706639], [0.2645751311064587, 'Iris-versicolor', 0.2645751311064587], [0.6557438524301997, 'Iris-versicolor', 0.6557438524301997], [0.8660254037844387, 'Iris-versicolor', 0.8660254037844387], [0.48989794855663593, 'Iris-versicolor', 0.48989794855663593], [1.1445523142259597, 'Iris-versicolor', 1.1445523142259597], [1.1618950038622253, 'Iris-versicolor', 1.1618950038622253], [1.2288205727444508, 'Iris-versicolor', 1.2288205727444508], [0.7549834435270754, 'Iris-versicolor', 0.7549834435270754], [0.9643650760992954, 'Iris-versicolor', 0.9643650760992954], [1.044030650891055, 'Iris-versicolor', 1.044030650891055], [0.7348469228349537, 'Iris-versicolor', 0.7348469228349537], [0.5744562646538031, 'Iris-versicolor', 0.5744562646538031], [0.6164414002968979, 'Iris-versicolor', 0.6164414002968979], [0.8306623862918082, 'Iris-versicolor', 0.8306623862918082], [1.0295630140987002, 'Iris-versicolor', 1.0295630140987002], [0.9591663046625443, 'Iris-versicolor', 0.9591663046625443], [0.4472135954999583, 'Iris-versicolor', 0.4472135954999583], [0.7416198487095667, 'Iris-versicolor', 0.7416198487095667], [1.846618531261939, 'Iris-versicolor', 1.846618531261939], [0.8306623862918081, 'Iris-versicolor', 0.8306623862918081], [0.721110255092798, 'Iris-versicolor', 0.721110255092798], [0.7071067811865477, 'Iris-versicolor', 0.7071067811865477], [0.20000000000000018, 'Iris-versicolor', 0.20000000000000018], [1.8920887928424504, 'Iris-versicolor', 1.8920887928424504], [0.7348469228349537, 'Iris-versicolor', 0.7348469228349537], [2.1213203435596424, 'Iris-virginica', 2.1213203435596424], [1.1832159566199232, 'Iris-virginica', 1.1832159566199232], [1.9235384061671348, 'Iris-virginica', 1.9235384061671348], [1.3964240043768938, 'Iris-virginica', 1.3964240043768938], [1.7549928774784245, 'Iris-virginica', 1.7549928774784245], [2.7166155414412243, 'Iris-virginica', 2.7166155414412243], [1.6155494421403513, 'Iris-virginica', 1.6155494421403513], [2.2494443758403984, 'Iris-virginica', 2.2494443758403984], [1.6583123951777, 'Iris-virginica', 1.6583123951777], [2.41039415863879, 'Iris-virginica', 2.41039415863879], [1.1090536506409416, 'Iris-virginica', 1.1090536506409416], [1.1832159566199232, 'Iris-virginica', 1.1832159566199232], [1.5, 'Iris-virginica', 1.5], [1.2767145334803707, 'Iris-virginica', 1.2767145334803707], [1.489966442575134, 'Iris-virginica', 1.489966442575134], [1.445683229480096, 'Iris-virginica', 1.445683229480096], [1.3076696830622023, 'Iris-virginica', 1.3076696830622023], [3.01164406927512, 'Iris-virginica', 3.01164406927512], [3.0886890422961004, 'Iris-virginica', 3.0886890422961004], [1.0862780491200217, 'Iris-virginica', 1.0862780491200217], [1.8165902124584952, 'Iris-virginica', 1.8165902124584952], [1.2247448713915898, 'Iris-virginica', 1.2247448713915898], [2.819574435974337, 'Iris-virginica', 2.819574435974337], [0.8124038404635964, 'Iris-virginica', 0.8124038404635964], [1.6881943016134136, 'Iris-virginica', 1.6881943016134136], [1.9672315572906003, 'Iris-virginica', 1.9672315572906003], [0.7416198487095663, 'Iris-virginica', 0.7416198487095663], [0.8426149773176365, 'Iris-virginica', 0.8426149773176365], [1.5297058540778354, 'Iris-virginica', 1.5297058540778354], [1.729161646579058, 'Iris-virginica', 1.729161646579058], [2.1470910553583886, 'Iris-virginica', 2.1470910553583886], [2.821347195933177, 'Iris-virginica', 2.821347195933177], [1.5842979517754858, 'Iris-virginica', 1.5842979517754858], [0.8366600265340753, 'Iris-virginica', 0.8366600265340753], [1.3711309200802089, 'Iris-virginica', 1.3711309200802089], [2.4372115213907874, 'Iris-virginica', 2.4372115213907874], [1.7776388834631176, 'Iris-virginica', 1.7776388834631176], [1.3152946437965907, 'Iris-virginica', 1.3152946437965907], [0.8185352771872452, 'Iris-virginica', 0.8185352771872452], [1.46287388383278, 'Iris-virginica', 1.46287388383278], [1.7406895185529208, 'Iris-virginica', 1.7406895185529208], [1.38924439894498, 'Iris-virginica', 1.38924439894498], [1.1832159566199232, 'Iris-virginica', 1.1832159566199232], [1.9519221295943137, 'Iris-virginica', 1.9519221295943137], [1.9104973174542803, 'Iris-virginica', 1.9104973174542803], [1.3820274961085255, 'Iris-virginica', 1.3820274961085255], [1.148912529307606, 'Iris-virginica', 1.148912529307606], [1.58113883008419, 'Iris-virginica', 1.58113883008419], [1.0723805294763606, 'Iris-virginica', 1.0723805294763606]]

In [51]:
sorted_distance_list[:3]

[[3.416138170507745, 'Iris-setosa', 3.416138170507745],
 [3.4467375879228173, 'Iris-setosa', 3.4467375879228173],
 [3.6318039594669758, 'Iris-setosa', 3.6318039594669758]]

In [53]:
class_list = []
for i in range(3):
    class_info = sorted_distance_list[i][0]
    class_list.append(class_info)

In [54]:
[i[0] for i in sorted_distance_list]

[3.416138170507745,
 3.4467375879228173,
 3.6318039594669758,
 3.511409973215888,
 3.474190553208042,
 3.0935416596516037,
 3.5916569992135945,
 3.3555923471125038,
 3.6905284174491872,
 3.4014702703389896,
 3.269556544854363,
 3.3630343441600474,
 4.012480529547776,
 3.5199431813596083,
 3.374907406137241,
 3.4365680554879168,
 3.385262175962152,
 3.009983388658482,
 3.3674916480965473,
 3.036445290137795,
 3.3136083051561784,
 3.9786932528155523,
 3.0413812651491097,
 3.1272991542223783,
 3.2357379374726873,
 3.2109188716004646,
 3.2939338184001206,
 3.363034344160048,
 3.388214869219483,
 3.3316662497915366,
 3.146426544510455,
 3.4871191548325386,
 3.4813790371058424,
 3.4014702703389896,
 3.5874782229304194,
 3.3734255586866007,
 3.4014702703389896,
 3.7709415269929605,
 3.3151168908501556,
 3.509985754956849,
 3.737646318206152,
 3.7815340802378077,
 3.1780497164141406,
 3.01164406927512,
 3.4612136599753565,
 3.3166247903554,
 3.598610843089317,
 3.301514803843836,
 3.426368339802363,
 0.7874007874011811,
 0.4123105625617663,
 0.830662386291808,
 1.1224972160321827,
 0.3872983346207415,
 0.7348469228349537,
 0.6480740698407863,
 1.8947295321496416,
 0.3605551275463984,
 1.284523257866513,
 1.8708286933869709,
 0.5567764362830021,
 0.9110433579144298,
 0.5099019513592792,
 1.0630145812734653,
 0.38729833462074176,
 0.8544003745317538,
 0.7280109889280523,
 0.7810249675906652,
 1.0000000000000004,
 0.9165151389911681,
 0.4358898943540677,
 0.7549834435270755,
 0.5196152422706639,
 0.2645751311064587,
 0.6557438524301997,
 0.8660254037844387,
 0.48989794855663593,
 1.1445523142259597,
 1.1618950038622253,
 1.2288205727444508,
 0.7549834435270754,
 0.9643650760992954,
 1.044030650891055,
 0.7348469228349537,
 0.5744562646538031,
 0.6164414002968979,
 0.8306623862918082,
 1.0295630140987002,
 0.9591663046625443,
 0.4472135954999583,
 0.7416198487095667,
 1.846618531261939,
 0.8306623862918081,
 0.721110255092798,
 0.7071067811865477,
 0.20000000000000018,
 1.8920887928424504,
 0.7348469228349537,
 2.1213203435596424,
 1.1832159566199232,
 1.9235384061671348,
 1.3964240043768938,
 1.7549928774784245,
 2.7166155414412243,
 1.6155494421403513,
 2.2494443758403984,
 1.6583123951777,
 2.41039415863879,
 1.1090536506409416,
 1.1832159566199232,
 1.5,
 1.2767145334803707,
 1.489966442575134,
 1.445683229480096,
 1.3076696830622023,
 3.01164406927512,
 3.0886890422961004,
 1.0862780491200217,
 1.8165902124584952,
 1.2247448713915898,
 2.819574435974337,
 0.8124038404635964,
 1.6881943016134136,
 1.9672315572906003,
 0.7416198487095663,
 0.8426149773176365,
 1.5297058540778354,
 1.729161646579058,
 2.1470910553583886,
 2.821347195933177,
 1.5842979517754858,
 0.8366600265340753,
 1.3711309200802089,
 2.4372115213907874,
 1.7776388834631176,
 1.3152946437965907,
 0.8185352771872452,
 1.46287388383278,
 1.7406895185529208,
 1.38924439894498,
 1.1832159566199232,
 1.9519221295943137,
 1.9104973174542803,
 1.3820274961085255,
 1.148912529307606,
 1.58113883008419,
 1.0723805294763606]

In [55]:
predicted_class = pd.Series(class_list).value_counts().idxmax()
predicted_class

np.float64(3.416138170507745)